Starting bulk prediction analysis at Fri Mar 28 13:58:32 PDT 2025
----------------------------------------
Running model: rf, target: form
Starting bulk prediction analysis...
Loading data...
[1mData loading completed: 0.01 seconds[0m
Preprocessing data...
Scaling features...
[1mFeature scaling completed: 0.00 seconds[0m
Setting up RF model...
Performing Bayesian Optimization...
Traceback (most recent call last):
  File "/Users/jiuy97/bin/tools/tetra/bulk_pred.py", line 1030, in <module>
    main() 
    ^^^^^^
  File "/Users/jiuy97/bin/tools/tetra/bulk_pred.py", line 639, in main
    cv=cv,
       ^^
NameError: name 'cv' is not defined. Did you mean: 'c'?
Running model: rf, target: form, row: 3d
Starting bulk prediction analysis...
Loading data...
[1mData loading completed: 0.01 seconds[0m
Preprocessing data...
Scaling features...
[1mFeature scaling completed: 0.00 seconds[0m
Setting up RF model...
Performing Bayesian Optimization...
Traceback (most recent call last):
  File "/Users/jiuy97/bin/tools/tetra/bulk_pred.py", line 1030, in <module>
    main() 
    ^^^^^^
  File "/Users/jiuy97/bin/tools/tetra/bulk_pred.py", line 639, in main
    cv=cv,
       ^^
NameError: name 'cv' is not defined. Did you mean: 'c'?
Running model: rf, target: form, row: 4d
Starting bulk prediction analysis...
Loading data...
[1mData loading completed: 0.01 seconds[0m
Preprocessing data...
Scaling features...
[1mFeature scaling completed: 0.00 seconds[0m
Setting up RF model...
Performing Bayesian Optimization...
Traceback (most recent call last):
  File "/Users/jiuy97/bin/tools/tetra/bulk_pred.py", line 1030, in <module>
    main() 
    ^^^^^^
  File "/Users/jiuy97/bin/tools/tetra/bulk_pred.py", line 639, in main
    cv=cv,
       ^^
NameError: name 'cv' is not defined. Did you mean: 'c'?
Running model: rf, target: form, row: 5d
